// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.10
// source: api/enums/communication.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phone int32

const (
	Phone_UNKNOWN   Phone = 0
	Phone_MOBILE    Phone = 1
	Phone_FAX_HOME  Phone = 2
	Phone_FAX_WORK  Phone = 3
	Phone_FAX_OTHER Phone = 4
	Phone_HOME      Phone = 5
	Phone_MAIN      Phone = 6
	Phone_WORK      Phone = 7
	Phone_CUST_SUP  Phone = 8
)

// Enum value maps for Phone.
var (
	Phone_name = map[int32]string{
		0: "UNKNOWN",
		1: "MOBILE",
		2: "FAX_HOME",
		3: "FAX_WORK",
		4: "FAX_OTHER",
		5: "HOME",
		6: "MAIN",
		7: "WORK",
		8: "CUST_SUP",
	}
	Phone_value = map[string]int32{
		"UNKNOWN":   0,
		"MOBILE":    1,
		"FAX_HOME":  2,
		"FAX_WORK":  3,
		"FAX_OTHER": 4,
		"HOME":      5,
		"MAIN":      6,
		"WORK":      7,
		"CUST_SUP":  8,
	}
)

func (x Phone) Enum() *Phone {
	p := new(Phone)
	*p = x
	return p
}

func (x Phone) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phone) Descriptor() protoreflect.EnumDescriptor {
	return file_api_enums_communication_proto_enumTypes[0].Descriptor()
}

func (Phone) Type() protoreflect.EnumType {
	return &file_api_enums_communication_proto_enumTypes[0]
}

func (x Phone) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phone.Descriptor instead.
func (Phone) EnumDescriptor() ([]byte, []int) {
	return file_api_enums_communication_proto_rawDescGZIP(), []int{0}
}

var File_api_enums_communication_proto protoreflect.FileDescriptor

var file_api_enums_communication_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2a, 0x77, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49,
	0x4c, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x41, 0x58, 0x5f, 0x48, 0x4f, 0x4d, 0x45,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x41, 0x58, 0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x03,
	0x12, 0x0d, 0x0a, 0x09, 0x46, 0x41, 0x58, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x04, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x4f, 0x4d, 0x45, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x49,
	0x4e, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x07, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x55, 0x53, 0x54, 0x5f, 0x53, 0x55, 0x50, 0x10, 0x08, 0x42, 0x4c, 0x0a, 0x17, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x72, 0x6d, 0x63, 0x67, 0x75, 0x69, 0x6e, 0x6e, 0x65, 0x73,
	0x73, 0x2f, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_enums_communication_proto_rawDescOnce sync.Once
	file_api_enums_communication_proto_rawDescData = file_api_enums_communication_proto_rawDesc
)

func file_api_enums_communication_proto_rawDescGZIP() []byte {
	file_api_enums_communication_proto_rawDescOnce.Do(func() {
		file_api_enums_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_enums_communication_proto_rawDescData)
	})
	return file_api_enums_communication_proto_rawDescData
}

var file_api_enums_communication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_enums_communication_proto_goTypes = []interface{}{
	(Phone)(0), // 0: google.retail.enums.communication.Phone
}
var file_api_enums_communication_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_enums_communication_proto_init() }
func file_api_enums_communication_proto_init() {
	if File_api_enums_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_enums_communication_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_enums_communication_proto_goTypes,
		DependencyIndexes: file_api_enums_communication_proto_depIdxs,
		EnumInfos:         file_api_enums_communication_proto_enumTypes,
	}.Build()
	File_api_enums_communication_proto = out.File
	file_api_enums_communication_proto_rawDesc = nil
	file_api_enums_communication_proto_goTypes = nil
	file_api_enums_communication_proto_depIdxs = nil
}
