---
description: >
  Geekdoc is a simple Hugo theme for documentations. It is intentionally designed as a fast and lean theme
  and may not fit the requirements of complex projects. If a more feature-complete theme is required
  there are a lot of good alternatives out there.
images:
  - "socialmedia2.png"

geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://github.com/rrmcguinness/google-retail-cloud
geekdocEditPath: edit/main/docs

geekdocSearch: true
geekdocSearchShowParent: true

geekdocLegalNotice: https://policies.google.com/terms?hl=en&fg=1
geekdocPrivacyPolicy: https://policies.google.com/privacy?hl=en&fg=1

geekdocImageLazyLoading: true
geekdocDarkModeDim: true
