// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.10
// source: api/promotions/model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RebateProgram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EffectiveDate  *timestamppb.Timestamp   `protobuf:"bytes,3,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	ExpirationDate *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	Sponsor        *RebateProgram_Sponsor   `protobuf:"bytes,5,opt,name=sponsor,proto3" json:"sponsor,omitempty"`
	Processor      *RebateProgram_Processor `protobuf:"bytes,6,opt,name=processor,proto3" json:"processor,omitempty"`
}

func (x *RebateProgram) Reset() {
	*x = RebateProgram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebateProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebateProgram) ProtoMessage() {}

func (x *RebateProgram) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebateProgram.ProtoReflect.Descriptor instead.
func (*RebateProgram) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{0}
}

func (x *RebateProgram) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RebateProgram) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RebateProgram) GetEffectiveDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveDate
	}
	return nil
}

func (x *RebateProgram) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *RebateProgram) GetSponsor() *RebateProgram_Sponsor {
	if x != nil {
		return x.Sponsor
	}
	return nil
}

func (x *RebateProgram) GetProcessor() *RebateProgram_Processor {
	if x != nil {
		return x.Processor
	}
	return nil
}

type CustomerRebateAccountProgram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomerRebateAccountProgram) Reset() {
	*x = CustomerRebateAccountProgram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRebateAccountProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRebateAccountProgram) ProtoMessage() {}

func (x *CustomerRebateAccountProgram) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRebateAccountProgram.ProtoReflect.Descriptor instead.
func (*CustomerRebateAccountProgram) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{1}
}

type CustomerRebateAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId      string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	RebateProgramId []string `protobuf:"bytes,3,rep,name=rebate_program_id,json=rebateProgramId,proto3" json:"rebate_program_id,omitempty"`
}

func (x *CustomerRebateAccount) Reset() {
	*x = CustomerRebateAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRebateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRebateAccount) ProtoMessage() {}

func (x *CustomerRebateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRebateAccount.ProtoReflect.Descriptor instead.
func (*CustomerRebateAccount) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerRebateAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerRebateAccount) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerRebateAccount) GetRebateProgramId() []string {
	if x != nil {
		return x.RebateProgramId
	}
	return nil
}

type CustomerRebateClaim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomerRebateClaim) Reset() {
	*x = CustomerRebateClaim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRebateClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRebateClaim) ProtoMessage() {}

func (x *CustomerRebateClaim) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRebateClaim.ProtoReflect.Descriptor instead.
func (*CustomerRebateClaim) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{3}
}

type CustomerRewardRebateLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CustomerRewardRebateLineItem) Reset() {
	*x = CustomerRewardRebateLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRewardRebateLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRewardRebateLineItem) ProtoMessage() {}

func (x *CustomerRewardRebateLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRewardRebateLineItem.ProtoReflect.Descriptor instead.
func (*CustomerRewardRebateLineItem) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{4}
}

type RebateClaimDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RebateClaimDocument) Reset() {
	*x = RebateClaimDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebateClaimDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebateClaimDocument) ProtoMessage() {}

func (x *RebateClaimDocument) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebateClaimDocument.ProtoReflect.Descriptor instead.
func (*RebateClaimDocument) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{5}
}

type RebateProcessor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RebateProcessor) Reset() {
	*x = RebateProcessor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebateProcessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebateProcessor) ProtoMessage() {}

func (x *RebateProcessor) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebateProcessor.ProtoReflect.Descriptor instead.
func (*RebateProcessor) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{6}
}

type RebateSponsor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RebateSponsor) Reset() {
	*x = RebateSponsor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebateSponsor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebateSponsor) ProtoMessage() {}

func (x *RebateSponsor) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebateSponsor.ProtoReflect.Descriptor instead.
func (*RebateSponsor) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{7}
}

type RebateProgram_Sponsor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartyId string `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
}

func (x *RebateProgram_Sponsor) Reset() {
	*x = RebateProgram_Sponsor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebateProgram_Sponsor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebateProgram_Sponsor) ProtoMessage() {}

func (x *RebateProgram_Sponsor) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebateProgram_Sponsor.ProtoReflect.Descriptor instead.
func (*RebateProgram_Sponsor) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RebateProgram_Sponsor) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type RebateProgram_Processor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartyId string `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
}

func (x *RebateProgram_Processor) Reset() {
	*x = RebateProgram_Processor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_promotions_model_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebateProgram_Processor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebateProgram_Processor) ProtoMessage() {}

func (x *RebateProgram_Processor) ProtoReflect() protoreflect.Message {
	mi := &file_api_promotions_model_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebateProgram_Processor.ProtoReflect.Descriptor instead.
func (*RebateProgram_Processor) Descriptor() ([]byte, []int) {
	return file_api_promotions_model_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RebateProgram_Processor) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

var File_api_promotions_model_proto protoreflect.FileDescriptor

var file_api_promotions_model_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x03, 0x0a, 0x0d, 0x52,
	0x65, 0x62, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x41, 0x0a, 0x0e, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x07, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x07, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x52, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x1a, 0x24, 0x0a, 0x07, 0x53, 0x70,
	0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64,
	0x1a, 0x26, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x74, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x62, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x72,
	0x65, 0x62, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x15,
	0x0a, 0x13, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f,
	0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x22,
	0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x62, 0x61, 0x74, 0x65, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72,
	0x42, 0x5f, 0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x01, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x72, 0x6d, 0x63, 0x67, 0x75, 0x69, 0x6e, 0x6e, 0x65, 0x73,
	0x73, 0x2f, 0x72, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_promotions_model_proto_rawDescOnce sync.Once
	file_api_promotions_model_proto_rawDescData = file_api_promotions_model_proto_rawDesc
)

func file_api_promotions_model_proto_rawDescGZIP() []byte {
	file_api_promotions_model_proto_rawDescOnce.Do(func() {
		file_api_promotions_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_promotions_model_proto_rawDescData)
	})
	return file_api_promotions_model_proto_rawDescData
}

var file_api_promotions_model_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_promotions_model_proto_goTypes = []interface{}{
	(*RebateProgram)(nil),                // 0: google.retail.promotions.pb.RebateProgram
	(*CustomerRebateAccountProgram)(nil), // 1: google.retail.promotions.pb.CustomerRebateAccountProgram
	(*CustomerRebateAccount)(nil),        // 2: google.retail.promotions.pb.CustomerRebateAccount
	(*CustomerRebateClaim)(nil),          // 3: google.retail.promotions.pb.CustomerRebateClaim
	(*CustomerRewardRebateLineItem)(nil), // 4: google.retail.promotions.pb.CustomerRewardRebateLineItem
	(*RebateClaimDocument)(nil),          // 5: google.retail.promotions.pb.RebateClaimDocument
	(*RebateProcessor)(nil),              // 6: google.retail.promotions.pb.RebateProcessor
	(*RebateSponsor)(nil),                // 7: google.retail.promotions.pb.RebateSponsor
	(*RebateProgram_Sponsor)(nil),        // 8: google.retail.promotions.pb.RebateProgram.Sponsor
	(*RebateProgram_Processor)(nil),      // 9: google.retail.promotions.pb.RebateProgram.Processor
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
}
var file_api_promotions_model_proto_depIdxs = []int32{
	10, // 0: google.retail.promotions.pb.RebateProgram.effective_date:type_name -> google.protobuf.Timestamp
	10, // 1: google.retail.promotions.pb.RebateProgram.expiration_date:type_name -> google.protobuf.Timestamp
	8,  // 2: google.retail.promotions.pb.RebateProgram.sponsor:type_name -> google.retail.promotions.pb.RebateProgram.Sponsor
	9,  // 3: google.retail.promotions.pb.RebateProgram.processor:type_name -> google.retail.promotions.pb.RebateProgram.Processor
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_promotions_model_proto_init() }
func file_api_promotions_model_proto_init() {
	if File_api_promotions_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_promotions_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebateProgram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRebateAccountProgram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRebateAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRebateClaim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRewardRebateLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebateClaimDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebateProcessor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebateSponsor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebateProgram_Sponsor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_promotions_model_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebateProgram_Processor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_promotions_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_promotions_model_proto_goTypes,
		DependencyIndexes: file_api_promotions_model_proto_depIdxs,
		MessageInfos:      file_api_promotions_model_proto_msgTypes,
	}.Build()
	File_api_promotions_model_proto = out.File
	file_api_promotions_model_proto_rawDesc = nil
	file_api_promotions_model_proto_goTypes = nil
	file_api_promotions_model_proto_depIdxs = nil
}
